apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss
  spec:
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: my-mariadb-container
          image: mysql
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-vars
                  key: DB_PASSWORD
            - name: MYSQL_USER_NAME 
              valueFrom:
                configMapKeyRef:
                  name: my-vars
                  key: DB_USER  
  selector:
    matchLabels:
      app: mariadb
  replicas: 3

          