version:  "3.8"
services: 
  backendimg:
    build: /root/Dockerimage_studentapp_threetier/Backend/
    container_name : backend
    ports: 
      - "8080:8080"
    network_mode:
        bridge
  frontendimg:  
    build:  /root/Dockerimage_studentapp_threetier/Frontend/
    container_name: frontend
    ports: 
      - "80:80"
    depends_on: 
      - backendimg
    network_mode:
        bridge
    
